ARG FLAVOR=${TARGETARCH}

ARG ROCMVERSION=6.1.2
ARG JETPACK5VERSION=r35.4.1
ARG JETPACK6VERSION=r36.2.0
ARG CMAKEVERSION=3.31.2

FROM cr.loongnix.cn/loongson/loongnix-server:8.4 AS base
ARG CMAKEVERSION
RUN yum update -y && yum install -y tar devtoolset-10-libstdc++ devtoolset-10-gcc devtoolset-10-gcc-c++  devtoolset-10-libstdc++-static devtoolset-10-libstdc++-devel devtoolset-10-libgcc make
COPY CMakeLists.txt CMakePresets.json ./
COPY ml/backend/ggml/ggml ml/backend/ggml/ggml
ENV LDFLAGS=-s

FROM base AS cpu
ARG CMAKEVERSION
#COPY cmake-3.31.2-linux-loongarch64.tar.gz /tmp
#RUN tar -xzvf /tmp/cmake-${CMAKEVERSION}-linux-$(uname -m).tar.gz -C /usr/local --strip-components 1
RUN curl -fsSL http://cloud.loongnix.cn/releases/loongarch64/Kitware/CMake/${CMAKEVERSION}/cmake-${CMAKEVERSION}-linux-$(uname -m).tar.gz | tar xz -C /usr/local --strip-components 1
ENV PATH=/opt/rh/devtoolset-10/root/usr/bin:$PATH
RUN cp /opt/rh/devtoolset-10/root/usr/lib/libstdc++.so.6* /lib64/
RUN --mount=type=cache,target=/root/.ccache \
   cmake --preset 'CPU' \
        && cmake --build --parallel --preset 'CPU' \
        && cmake --install build --component CPU --strip 

FROM scratch AS archive
COPY --from=cpu dist/lib/ollama /lib/ollama
#COPY --from=build /bin/ollama /bin/ollama
COPY ollama /bin/ollama

FROM cr.loongnix.cn/loongson/loongnix:20
RUN apt-get update \
    && apt-get install -y ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
COPY --from=archive /bin /usr/bin
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
COPY --from=archive /lib/ollama /usr/lib/ollama
COPY --from=cpu /opt/rh/devtoolset-10/root/usr/lib/libstdc++.so.6* /lib64/
ENV LD_LIBRARY_PATH=/lib64:$LD_LIBRARY_PATH
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility
ENV NVIDIA_VISIBLE_DEVICES=all
ENV OLLAMA_HOST=0.0.0.0:11434
EXPOSE 11434
ENTRYPOINT ["/usr/bin/ollama"]
CMD ["serve"]
